const EVENT_NAMES = {
  MESSAGE_EMITTED: "MESSAGE_EMITTED",
  VIDEO_PAUSED: "VIDEO_PAUSED",
  VIDEO_PLAYED: "VIDEO_PLAYED",
  USER_JOINED_ROOM: "USER_JOINED_ROOM",
  USER_READY: "USER_READY",
} as const;

export default EVENT_NAMES;
