export const EVENT_NAMES = {
  JOIN_ROOM: "join_room",
  SET_ID: "set_id",
  KICK: "kick",
  UNSYNC: "unsync",
  USER_INITIAL_DATA: "user_initial_data",
  USER_READY: "user_ready",
  USER_NOT_READY: "user_notReady",
  USER_WAITING_FOR_DATA: "user_waitingForData",
  USER_DISCONNECTED: "user_disconnected",
  MESSAGE_EMITTED: "MESSAGE_EMITTED",
  MEDIA_PAUSED: "media_paused",
  MEDIA_PLAYED: "media_played",
  MEDIA_SEEKED: "media_seeked",
  GET_USER: "GET_USER",
} as const;
