export const EVENT_NAMES = {
  USER_JOINED_ROOM: "user_joined_room",
  USER_WAITING_FOR_DATA: "user_waiting_for_data",
  MESSAGE_EMITTED: "MESSAGE_EMITTED",
  VIDEO_PAUSED: "VIDEO_PAUSED",
  VIDEO_PLAYED: "VIDEO_PLAYED",
  USER_READY: "USER_READY",
  GET_USER: "GET_USER",
} as const;
