export const EVENT_NAMES = {
  JOIN_ROOM: "JOIN_ROOM",
  MESSAGE_EMITTED: "MESSAGE_EMITTED",
  VIDEO_PAUSED: "VIDEO_PAUSED",
  VIDEO_PLAYED: "VIDEO_PLAYED",
  USER_JOINED_ROOM: "USER_JOINED_ROOM",
  USER_READY: "USER_READY",
  GET_USER: "GET_USER",
} as const;
